### ISSUE TITLE
Support .wmbt  2

### ISSUE THREAD

**Issue by Digote** [ArchLeaders/MsbtToYaml#6] opened 2024-05-25 20:12 UTC
I know the tool is for .msbt files, but I found some similarities in the .wmbt file. If anyone can provide support for this as well, if I’m not mistaken, currently we only have reading support for the Switch-Toolbox tool.

Game: WarioWare™: Move It!

File

[File.zip](https://github.com/ArchLeaders/MsbtToYaml/files/15444881/File.zip)

------------------------------------------------------------------------------------------------------------------------

Obs. This file seems to have a different error.

Error:

![wmbt-MOVE_IT](https://github.com/ArchLeaders/MsbtToYaml/assets/45742711/bf8d0879-eb2a-4073-9c51-3c185ac99dee)

**Comment by ArchLeaders** [comment] 2024-05-25 20:21
Duplicate of #5

**Closed as not planned by ArchLeaders** 2024-05-25 20:21 UTC
